### ISSUE TITLE
"Server Quiz" asks re pokeapi.co, but maybe answer is out of date?

### ISSUE THREAD

**Issue by brigj1** [learn-co-curriculum/phase-1-quiz-communicating-with-the-server#1]
### Canvas Link

https://learning.flatironschool.com/courses/5185/quizzes/29391

### Concern

Question 5 conveniently supplies a link to https://pokeapi.co/ and asks which 'fetch' snippets would work.
It's not obvious from viewing that URL whether we are using the right domain name in the potential answers below to use the API. Trying each of the sample answers in my Console returns an error message complaining of:
No 'Access-Control-Allow-Origin' header is present on the requested resource.

So it seems like none of the suggested answers would allow her to send/log the info.

Question 5:

Yuli is making an application that interacts with the Pokemon API (https://pokeapi.co/). The Pokemon API uses JSON as its response format. Which of the following code snippets would allow her to send a request to the API and log a Pokemon object to the console?
Group of answer choices

fetch("https://pokeapi.co/").then((pokemon) => console.log(pokemon));

fetch("https://pokeapi.co/")
  .then((resp) => resp.text())
  .then((pokemon) => console.log(pokemon));

I don't know

fetch("https://pokeapi.co/")
  .then((resp) => resp.json())
  .then((pokemon) => console.log(pokemon));

### Suggested Changes

It seems like none of the suggested answers for quiz question 5 would allow Yuli to send/log the info.
Update the question and/or answer?
Maybe I am missing something?

**Comment by lizbur10** [comment]
Hi @brigj1 ! What the question is intended to ask is which of the snippets provided is set up properly (has the correct syntax) for making a fetch request to the api, getting a pokemon object as the return value, and logging that object to the screen. The functioning of the API itself is not intended to be part of the question, but I can see why that isn't clear. I have revised the question to take out the reference to a specific API.

Thanks!

**Comment by brigj1** [comment]
Hi Liz,
Thanks, that's useful.
Yes, it seems like a general question fits the flow, but the setup
referenced a specific API, which opens the challenge to looking it up to
see if the API has special considerations.

That is, we are asked to choose between 'resp.text' and 'resp.json' (and
other stuff) as the one possible answer. (The answers don't allow checking
multiple entries as acceptable) But my memory said that 'resp.text' was
valid, as seems described here,
https://developer.mozilla.org/en-US/docs/Web/API/Response/text, so maybe
deciding between the two would be informed by checking the API's docs.
(Maybe they'd say "We only do 'resp.text'!")

I got credit for choosing 'resp.json' but felt a disconnect from not also
being able to choose 'resp.text'. I would like to have had the chance to
also choose that one, even if it's wrong for some reason.

Maybe I'm missing something, but if so, is that from how the question and
answer(s) are framed?

Thanks,
Brigham Johnson
